spring:
  profiles:
    active: dev,local

  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH

  liquibase:
    enabled: true
    contexts: dev

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true

  data:
    mongodb:
      host: localhost
      database: booklib
      port: 27017

  batch:
    job:
      enabled: false

#logging:
#  level:
#    ROOT: ERROR
#    liquibase: DEBUG

target:
  authors-collection: author
  genres-collection: genre
  books-collection: book

