server:
  port: 8089

spring:
  #  profiles:
  #    active: dev

  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH

  liquibase:
    enabled: true
    contexts: dev

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
#    show-sql: true

logging:
  level:
    ROOT: ERROR
#    liquibase: DEBUG
