#server:
#  port: 8089

spring:
  #  profiles:
  #    active: dev

  data:
    mongodb:
      host: server
      username: root
      password: scout
      database: booklib
      authentication-database: admin

mongock:
#  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - io.github.maxixcom.otus.booklib.mongock.changelog

#  datasource:
#    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH

#logging:
#  level:
#    ROOT: ERROR
#    liquibase: DEBUG
