spring:
  #  profiles:
  #    active: dev

  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH

  liquibase:
    enabled: true
    contexts: dev

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true

  data:
    rest:
      base-path: /datarest

#logging:
#  level:
#    ROOT: ERROR
#    liquibase: DEBUG

logging:
  file:
    name: app.log

management:
  endpoints:
    web:
      exposure:
        include: metrics,logfile,health
#        include: "*"
  endpoint:
    health:
      show-components: always
