spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
  liquibase:
    enabled: true
    contexts: dev
  h2:
    console:
      enabled: true

logging:
  level:
    liquibase: DEBUG